from typing import NewType
from typing import List, Set, Dict, Tuple, Optional

Char   = NewType('Char', int)

UInt8  = NewType('UInt8', int)
UInt16 = NewType('UInt16', int)
UInt32 = NewType('UInt32', int)
UInt64 = NewType('UInt64', int)

Int8   = NewType('Int8', int)
Int16  = NewType('Int16', int)
Int32  = NewType('Int32', int)
Int64  = NewType('Int64', int)

Interface_Type                      = NewType('Interface_Type', int)
Address_Type                        = NewType('Address_Type', int)

AemCommandStatus                    = NewType('AemCommandStatus', UInt16)
AaCommandStatus                     = NewType('AaCommandStatus', UInt16)
MvuCommandStatus                    = NewType('MvuCommandStatus', UInt16)
ControlStatus                       = NewType('ControlStatus', UInt16)
AecpSequenceID                      = NewType('AecpSequenceID', UInt16)

ConfigurationIndex                  = NewType('ConfigurationIndex', UInt16)
DescriptorIndex                     = NewType('DescriptorIndex', UInt16)

AudioUnitIndex                      = NewType('AudioUnitIndex', UInt16)
StreamIndex                         = NewType('StreamIndex', UInt16)
JackIndex                           = NewType('JackIndex', UInt16)
AvbInterfaceIndex                   = NewType('AvbInterfaceIndex', UInt16)
ClockSourceIndex                    = NewType('ClockSourceIndex', UInt16)
MemoryObjectIndex                   = NewType('MemoryObjectIndex', UInt16)
LocaleIndex                         = NewType('LocaleIndex', UInt16)
StringsIndex                        = NewType('StringsIndex', UInt16)
StreamPortIndex                     = NewType('StreamPortIndex', UInt16)
ExternalPortIndex                   = NewType('ExternalPortIndex', UInt16)
InternalPortIndex                   = NewType('InternalPortIndex', UInt16)
ClusterIndex                        = NewType('ClusterIndex', UInt16)
MapIndex                            = NewType('MapIndex', UInt16)
ControlIndex                        = NewType('ControlIndex', UInt16)
SignalSelectorIndex                 = NewType('SignalSelectorIndex', UInt16)
MixerIndex                          = NewType('MixerIndex', UInt16)
MatrixIndex                         = NewType('MatrixIndex', UInt16)
SignalSplitterIndex                 = NewType('SignalSplitterIndex', UInt16)
SignalCombinerIndex                 = NewType('SignalCombinerIndex', UInt16)
SignalDemultiplexerIndex            = NewType('SignalDemultiplexerIndex', UInt16)
SignalMultiplexerIndex              = NewType('SignalMultiplexerIndex', UInt16)
SignalTranscoderIndex               = NewType('SignalTranscoderIndex', UInt16)
ClockDomainIndex                    = NewType('ClockDomainIndex', UInt16)
ControlBlockIndex                   = NewType('ControlBlockIndex', UInt16)
TimingIndex                         = NewType('TimingIndex', UInt16)
PtpInstanceIndex                    = NewType('PtpInstanceIndex', UInt16)
PtpPortIndex                        = NewType('PtpPortIndex', UInt16)
OperationID                         = NewType('OperationID', UInt16)
BridgeIdentifier                    = NewType('BridgeIdentifier', UInt64)


AudioClusterFormat                  = NewType('AudioClusterFormat', UInt8)
ClockSourceType                     = NewType('ClockSourceType', UInt16)
DescriptorType                      = NewType('DescriptorType', UInt16)
JackType                            = NewType('JackType', UInt16)
MemoryObjectOperationType           = NewType('MemoryObjectOperationType', UInt16)
MemoryObjectType                    = NewType('MemoryObjectType', UInt16)
TimingAlgorithm                     = NewType('TimingAlgorithm', UInt16)
PtpPortType                         = NewType('PtpPortType', UInt16)
StandardControlType                 = NewType('StandardControlType', UInt64)
ProbingStatus                       = NewType('ProbingStatus', UInt8)
MsrpFailureCode                     = NewType('MsrpFailureCode', UInt8)

ControlValueUnit_Unit               = NewType('ControlValueUnit_Unit', UInt8)
ControlValueType_Type               = NewType('ControlValueType_Type', UInt16)

EntityCapability                    = NewType('EntityCapability', UInt32)
TalkerCapability                    = NewType('TalkerCapability', UInt16)
ListenerCapability                  = NewType('ListenerCapability', UInt16)
ControllerCapability                = NewType('ControllerCapability', UInt32)
ConnectionFlag                      = NewType('ConnectionFlag', UInt16)
StreamFlag                          = NewType('StreamFlag', UInt16)
JackFlag                            = NewType('JackFlag', UInt16)
AvbInterfaceFlag                    = NewType('AvbInterfaceFlag', UInt16)
ClockSourceFlag                     = NewType('ClockSourceFlag', UInt16)
PortFlag                            = NewType('PortFlag', UInt16)
PtpInstanceFlag                     = NewType('PtpInstanceFlag', UInt32)
PtpPortFlag                         = NewType('PtpPortFlag', UInt32)
StreamInfoFlag                      = NewType('StreamInfoFlag', UInt32)
StreamInfoFlagEx                    = NewType('StreamInfoFlagEx', UInt32)
AvbInfoFlag                         = NewType('AvbInfoFlag', UInt8)
EntityCounterValidFlag              = NewType('EntityCounterValidFlag', UInt32)
AvbInterfaceCounterValidFlag        = NewType('AvbInterfaceCounterValidFlag', UInt32)
ClockDomainCounterValidFlag         = NewType('ClockDomainCounterValidFlag', UInt32)
StreamInputCounterValidFlag         = NewType('StreamInputCounterValidFlag', UInt32)
StreamOutputCounterValidFlag        = NewType('StreamOutputCounterValidFlag', UInt32)
StreamOutputCounterValidFlag17221   = NewType('StreamOutputCounterValidFlag17221', UInt32)
MilanInfoFeaturesFlag               = NewType('MilanInfoFeaturesFlag', UInt32)
